<?php

namespace ContainerJYwqNPP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SEDBaYWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SEDBaYW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SEDBaYW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'aiRecommendationService' => ['privates', 'App\\Service\\AIRecommendationService', 'getAIRecommendationServiceService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'aiRecommendationService' => 'App\\Service\\AIRecommendationService',
            'entityManager' => '?',
        ]);
    }
}
