<?php

namespace ContainerJYwqNPP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAIRecommendationServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\AIRecommendationService' shared autowired service.
     *
     * @return \App\Service\AIRecommendationService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'AIRecommendationService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\AIRecommendationService'])) {
            return $container->privates['App\\Service\\AIRecommendationService'];
        }

        return $container->privates['App\\Service\\AIRecommendationService'] = new \App\Service\AIRecommendationService($a);
    }
}
