<?php

namespace Container8MtDqqj;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailer_MessageListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'mailer.message_listener' shared service.
     *
     * @return \Symfony\Component\Mailer\EventListener\MessageListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'mailer'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'MessageListener.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'mime'.\DIRECTORY_SEPARATOR.'Header'.\DIRECTORY_SEPARATOR.'Headers.php';

        $a = new \Symfony\Component\Mime\Header\Headers();
        $a->addHeader('from', ['Reaptn Agricultural App <noreply@reaptn.com>']);

        return $container->privates['mailer.message_listener'] = new \Symfony\Component\Mailer\EventListener\MessageListener($a);
    }
}
