<?php

namespace ContainerBdgypFg;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWeatherControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\WeatherController' shared autowired service.
     *
     * @return \App\Controller\Api\WeatherController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'WeatherController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'MockWeatherService.php';

        $container->services['App\\Controller\\Api\\WeatherController'] = $instance = new \App\Controller\Api\WeatherController(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), ($container->privates['App\\Service\\MockWeatherService'] ??= new \App\Service\MockWeatherService()));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Api\\WeatherController', $container));

        return $instance;
    }
}
