<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJYwqNPP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJYwqNPP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJYwqNPP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJYwqNPP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJYwqNPP\App_KernelDevDebugContainer([
    'container.build_hash' => 'JYwqNPP',
    'container.build_id' => '292d626f',
    'container.build_time' => 1740268674,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJYwqNPP');
