<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRp4cGjx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRp4cGjx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRp4cGjx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRp4cGjx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRp4cGjx\App_KernelDevDebugContainer([
    'container.build_hash' => 'Rp4cGjx',
    'container.build_id' => 'aab0be74',
    'container.build_time' => 1739673510,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRp4cGjx');
